name: asyncstate
description: This package will help you to call a loading in your async methods very easily, and you don't need to worried when it's is starting or finishing.
homepage: https://leonardoserrano.dev/
repository: https://github.com/DevLSerrano/asyncstate/
version: 3.0.0-dev.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
