name: asyncstate
description: This package will help you to call a loading in your async methods very easyly, and you don't need to worrie when it's is starting or finishing.
homepage: https://leonardoserrano.dev/
repository: https://github.com/DevLSerrano/asyncstate/
version: 1.0.0

environment:
  sdk: ">=2.15.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
